/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.DataClasses.UI;
using WorldSmith.Panels;
using WorldSmith.Dialogs;

namespace WorldSmith.DataClasses
{
	class DotaHero : DotaBaseUnit
	{
		[Category("General")]
		[Description("Enable/disable this hero.")]
		[DefaultValue(true)]
		public bool Enabled
		{
			get;
			set;
		}

		[Category("General")]
		[Description("Does this hero have bot AI implemented?")]
		[DefaultValue(false)]
		public bool BotImplemented
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(false)]
		public bool NewHero
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(false)]
		public bool HeroPool1
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(1)]
		public int HeroUnlockOrder
		{
			get;
			set;
		}

		[Category("General")]
		[Description("Enable/disable this hero in Captain's Mode.")]
		[DefaultValue(false)]
		public bool CMEnabled
		{
			get;
			set;
		}

		[Category("General")]
		[Description("No Description Set")]
		[DefaultValue(false)]
		public bool CMTournamentIgnore
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(false)]
		public bool new_player_enable
		{
			get;
			set;
		}

		[Category("Voice")]
		[Description("No Description Set")]
		[DefaultValue("")]
		public string VoiceBackgroundSound
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue("scenes\\default_idle.vcd")]
		public string IdleExpression
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue("")]
		public string HUD
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue("")]
		public string override_hero
		{
			get;
			set;
		}

	}
}
