/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	public partial class DotaItem : DotaAbility
	{
		public DotaItem(KeyValue kv)
			: base(kv)
		{
		}
		public DotaItem(string className)
			: base(className)
		{
		}
		[Category("General")]
		[Description("How much this item costs. This value is overriden by recipe requirements.")]
		[DefaultValue(0)]
		public int ItemCost
		{
			get
			{
				KeyValue kv = GetSubkey("ItemCost");
				return (kv == null ? 0 : kv.GetInt());
			}
			set
			{
				GetSubkey("ItemCost").Set(value.ToString());
			}
		}

		[Category("Charges")]
		[Description("How many charges this item starts with.")]
		[DefaultValue(0)]
		public int ItemInitialCharges
		{
			get
			{
				KeyValue kv = GetSubkey("ItemInitialCharges");
				return (kv == null ? 0 : kv.GetInt());
			}
			set
			{
				GetSubkey("ItemInitialCharges").Set(value.ToString());
			}
		}

		[Category("General")]
		[Description("No Description Set")]
		[DefaultValue(true)]
		public bool ItemCombinable
		{
			get
			{
				KeyValue kv = GetSubkey("ItemCombinable");
				return (kv == null ? true : kv.GetBool());
			}
			set
			{
				GetSubkey("ItemCombinable").Set(value.ToString());
			}
		}

		[Category("General")]
		[Description("No Description Set")]
		[DefaultValue(true)]
		public bool ItemPermanent
		{
			get
			{
				KeyValue kv = GetSubkey("ItemPermanent");
				return (kv == null ? true : kv.GetBool());
			}
			set
			{
				GetSubkey("ItemPermanent").Set(value.ToString());
			}
		}

		[Category("General")]
		[Description("If this item is stackable or not. Usually used for consumables.")]
		[DefaultValue(false)]
		public bool ItemStackable
		{
			get
			{
				KeyValue kv = GetSubkey("ItemStackable");
				return (kv == null ? false : kv.GetBool());
			}
			set
			{
				GetSubkey("ItemStackable").Set(value.ToString());
			}
		}

		[Category("General")]
		[Description("States if this item is a recipe or not.")]
		[DefaultValue(false)]
		public bool ItemRecipe
		{
			get
			{
				KeyValue kv = GetSubkey("ItemRecipe");
				return (kv == null ? false : kv.GetBool());
			}
			set
			{
				GetSubkey("ItemRecipe").Set(value.ToString());
			}
		}

		[Category("General")]
		[Description("States if you are able to drop this item on the ground.")]
		[DefaultValue(true)]
		public bool ItemDroppable
		{
			get
			{
				KeyValue kv = GetSubkey("ItemDroppable");
				return (kv == null ? true : kv.GetBool());
			}
			set
			{
				GetSubkey("ItemDroppable").Set(value.ToString());
			}
		}

		[Category("Purchase")]
		[Description("States whether or not you can purchase this item.")]
		[DefaultValue(true)]
		public bool ItemPurchasable
		{
			get
			{
				KeyValue kv = GetSubkey("ItemPurchasable");
				return (kv == null ? true : kv.GetBool());
			}
			set
			{
				GetSubkey("ItemPurchasable").Set(value.ToString());
			}
		}

		[Category("Purchase")]
		[Description("States whether or not you can sell this item.")]
		[DefaultValue(true)]
		public bool ItemSellable
		{
			get
			{
				KeyValue kv = GetSubkey("ItemSellable");
				return (kv == null ? true : kv.GetBool());
			}
			set
			{
				GetSubkey("ItemSellable").Set(value.ToString());
			}
		}

		[Category("Charges")]
		[Description("States whether or not this item requires charges.")]
		[DefaultValue(false)]
		public bool ItemRequiresCharges
		{
			get
			{
				KeyValue kv = GetSubkey("ItemRequiresCharges");
				return (kv == null ? false : kv.GetBool());
			}
			set
			{
				GetSubkey("ItemRequiresCharges").Set(value.ToString());
			}
		}

		[Category("General")]
		[Description("States whether or not you can destroy this item by attacking it.")]
		[DefaultValue(true)]
		public bool ItemKillable
		{
			get
			{
				KeyValue kv = GetSubkey("ItemKillable");
				return (kv == null ? true : kv.GetBool());
			}
			set
			{
				GetSubkey("ItemKillable").Set(value.ToString());
			}
		}

		[Category("General")]
		[Description("States whether or not you can disassemble this item.")]
		[DefaultValue(false)]
		public bool ItemDisassemblable
		{
			get
			{
				KeyValue kv = GetSubkey("ItemDisassemblable");
				return (kv == null ? false : kv.GetBool());
			}
			set
			{
				GetSubkey("ItemDisassemblable").Set(value.ToString());
			}
		}

		public enum ItemShareabilityEnum
		{
			ITEM_PARTIALLY_SHAREABLE,
			ITEM_FULLY_SHAREABLE,
			ITEM_FULLY_SHAREABLE_STACKING,
			ITEM_NOT_SHAREABLE,
		}

		[Category("General")]
		[Description("States whether or not you can share this item.")]
		[DefaultValue(ItemShareabilityEnum.ITEM_NOT_SHAREABLE)]
		public ItemShareabilityEnum ItemShareability
		{
			get
			{
				KeyValue kv = GetSubkey("ItemShareability");
				return (kv == null ? ItemShareabilityEnum.ITEM_NOT_SHAREABLE : kv.GetEnum<ItemShareabilityEnum>());
			}
			set
			{
				GetSubkey("ItemShareability").Set(value.ToString());
			}
		}

		[Category("Purchase")]
		[Description("States whether or not this item displays a notification when bought.")]
		[DefaultValue(false)]
		public bool ItemDeclaresPurchase
		{
			get
			{
				KeyValue kv = GetSubkey("ItemDeclaresPurchase");
				return (kv == null ? false : kv.GetBool());
			}
			set
			{
				GetSubkey("ItemDeclaresPurchase").Set(value.ToString());
			}
		}

		[Flags]
		public enum ItemDeclarationsFlags : long
		{
			DECLARE_PURCHASES_NONE = 0,
			DECLARE_PURCHASES_IN_SPEECH = 1,
			DECLARE_PURCHASES_TO_SPECTATORS = 2,
			DECLARE_PURCHASES_TO_TEAMMATES = 4,
		}

		[Editor(typeof(FlagEnumDialogUIEditor), typeof(System.Drawing.Design.UITypeEditor))]
		[Category("Purchase")]
		[Description("States the type of notification displayed when this item is purchased.")]
		[DefaultValue(ItemDeclarationsFlags.DECLARE_PURCHASES_NONE)]
		public ItemDeclarationsFlags ItemDeclarations
		{
			get
			{
				KeyValue kv = GetSubkey("ItemDeclarations");
				return (kv == null ? ItemDeclarationsFlags.DECLARE_PURCHASES_NONE : kv.GetEnum<ItemDeclarationsFlags>());
			}
			set
			{
				GetSubkey("ItemDeclarations").Set(value.ToString());
			}
		}

	}
}
