/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Apply %Action on %Target")]
	public partial class ActOnTargets : TargetedAction
	{
		public ActOnTargets(KeyValue kv)
			: base(kv)
		{
		}
		public ActOnTargets(string className)
			: base(className)
		{
		}
		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(typeof(ActionCollection), "Default")]
		public ActionCollection Action
		{
			get
			{
				return default(ActionCollection);
			}
			set
			{
				GetSubkey("Action").Set(value.ToString());
			}
		}

	}
}
