/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Apply %ModifierName on %Target")]
	public partial class ApplyModifier : TargetedAction
	{
		public ApplyModifier(KeyValue kv)
			: base(kv)
		{
		}
		public ApplyModifier(string className)
			: base(className)
		{
		}
		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue("")]
		public string ModifierName
		{
			get
			{
				KeyValue kv = GetSubkey("ModifierName");
				return (kv == null ? "" : kv.GetString());
			}
			set
			{
				KeyValue kv = GetSubkey("ModifierName");
				if(kv == null)
				{
					kv = new KeyValue("ModifierName");
					KeyValue.AddChild(kv);
				}
				kv.Set(value);
			}
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue Duration
		{
			get
			{
				KeyValue kv = GetSubkey("Duration");
				return (kv == null ? new NumberValue("Duration") : kv.GetNumberValue());
			}
			set
			{
				KeyValue kv = GetSubkey("Duration");
				if(kv == null)
				{
					kv = new KeyValue("Duration");
					KeyValue.AddChild(kv);
				}
				kv.Set(value);
			}
		}

	}
}
