/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	public partial class BaseAction : DotaDataObject
	{
		public BaseAction(KeyValue kv)
			: base(kv)
		{
		}
		public BaseAction(string className)
			: base(className)
		{
		}
	}
}
