/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Apply %CleavePercent percent of attack to all targets in %CleaveRadius units")]
	public partial class CleaveAttack : BaseAction
	{
		public CleaveAttack(KeyValue kv)
			: base(kv)
		{
		}
		public CleaveAttack(string className)
			: base(className)
		{
		}
		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue CleavePercent
		{
			get
			{
				KeyValue kv = GetSubkey("CleavePercent");
				return (kv == null ? new NumberValue("CleavePercent") : kv.GetNumberValue());
			}
			set
			{
				KeyValue kv = GetSubkey("CleavePercent");
				if(kv == null)
				{
					kv = new KeyValue("CleavePercent");
					KeyValue.AddChild(kv);
				}
				kv.Set(value);
			}
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue CleaveRadius
		{
			get
			{
				KeyValue kv = GetSubkey("CleaveRadius");
				return (kv == null ? new NumberValue("CleaveRadius") : kv.GetNumberValue());
			}
			set
			{
				KeyValue kv = GetSubkey("CleaveRadius");
				if(kv == null)
				{
					kv = new KeyValue("CleaveRadius");
					KeyValue.AddChild(kv);
				}
				kv.Set(value);
			}
		}

	}
}
