/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Apply %CleavePercent percent of attack to all targets in %CleaveRadius units")]
	public partial class CleaveAttack : BaseAction
	{
		public CleaveAttack(KeyValue kv)
			: base(kv)
		{
		}
		public CleaveAttack(string className)
			: base(className)
		{
		}
		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue CleavePercent
		{
			get
			{
				return default(NumberValue);
			}
			set
			{
				GetSubkey("CleavePercent").Set(value.ToString());
			}
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue CleaveRadius
		{
			get
			{
				return default(NumberValue);
			}
			set
			{
				GetSubkey("CleaveRadius").Set(value.ToString());
			}
		}

	}
}
