/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Create a thinking %ModifierName wall that is %Width by %Length units rotated %Rotation degrees at %Target")]
	public partial class CreateThinkerWall : CreateThinker
	{
		public CreateThinkerWall(KeyValue kv)
			: base(kv)
		{
		}
		public CreateThinkerWall(string className)
			: base(className)
		{
		}
		[Category("Misc")]
		[Description("int")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue Width
		{
			get
			{
				return default(NumberValue);
			}
			set
			{
				GetSubkey("Width").Set(value.ToString());
			}
		}

		[Category("Misc")]
		[Description("int")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue Length
		{
			get
			{
				return default(NumberValue);
			}
			set
			{
				GetSubkey("Length").Set(value.ToString());
			}
		}

		[Category("Misc")]
		[Description("rotation")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue Rotation
		{
			get
			{
				return default(NumberValue);
			}
			set
			{
				GetSubkey("Rotation").Set(value.ToString());
			}
		}

	}
}
