/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Create %ItemName within a %SpawnRadius unit radius around %Target with %ItemChargeCount charges and belongs to caster %BelongsToCaster")]
	public partial class CreateItem : TargetedAction
	{
		public CreateItem(KeyValue kv)
			: base(kv)
		{
		}
		public CreateItem(string className)
			: base(className)
		{
		}
		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue("")]
		public string ItemName
		{
			get
			{
				KeyValue kv = GetSubkey("ItemName");
				return (kv == null ? "" : kv.GetString());
			}
			set
			{
				GetSubkey("ItemName").Set(value.ToString());
			}
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue SpawnRadius
		{
			get
			{
				return default(NumberValue);
			}
			set
			{
				GetSubkey("SpawnRadius").Set(value.ToString());
			}
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue ItemChargeCount
		{
			get
			{
				return default(NumberValue);
			}
			set
			{
				GetSubkey("ItemChargeCount").Set(value.ToString());
			}
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue("")]
		public string BelongsToCaster
		{
			get
			{
				KeyValue kv = GetSubkey("BelongsToCaster");
				return (kv == null ? "" : kv.GetString());
			}
			set
			{
				GetSubkey("BelongsToCaster").Set(value.ToString());
			}
		}

	}
}
