/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Do %DamageAmount of %Type damage to %Target")]
	public partial class Damage : TargetedAction
	{
		public Damage(KeyValue kv)
			: base(kv)
		{
		}
		public Damage(string className)
			: base(className)
		{
		}
		public enum TypeEnum
		{
			DAMAGE_TYPE_COMPOSITE,
			DAMAGE_TYPE_HP_REMOVAL,
			DAMAGE_TYPE_MAGICAL,
			DAMAGE_TYPE_PHYSICAL,
			DAMAGE_TYPE_PURE,
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(TypeEnum.DAMAGE_TYPE_MAGICAL)]
		public TypeEnum Type
		{
			get
			{
				KeyValue kv = GetSubkey("Type");
				return (kv == null ? TypeEnum.DAMAGE_TYPE_MAGICAL : kv.GetEnum<TypeEnum>());
			}
			set
			{
				KeyValue kv = GetSubkey("Type");
				if(kv == null)
				{
					kv = new KeyValue("Type");
					KeyValue.AddChild(kv);
				}
				kv.Set(value);
			}
		}

		[Category("Misc")]
		[Description("int")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue DamageAmount
		{
			get
			{
				KeyValue kv = GetSubkey("DamageAmount");
				return (kv == null ? new NumberValue("DamageAmount") : kv.GetNumberValue());
			}
			set
			{
				KeyValue kv = GetSubkey("DamageAmount");
				if(kv == null)
				{
					kv = new KeyValue("DamageAmount");
					KeyValue.AddChild(kv);
				}
				kv.Set(value);
			}
		}

	}
}
