/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Do %Action after a %Delay second delay")]
	public partial class DelayedAction : BaseAction
	{
		public DelayedAction(KeyValue kv)
			: base(kv)
		{
		}
		public DelayedAction(string className)
			: base(className)
		{
		}
		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(typeof(ActionCollection), "Default")]
		public ActionCollection Action
		{
			get
			{
				return default(ActionCollection);
			}
			set
			{
				GetSubkey("Action").Set(value.ToString());
			}
		}

		[Category("Misc")]
		[Description("float")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue Delay
		{
			get
			{
				return default(NumberValue);
			}
			set
			{
				GetSubkey("Delay").Set(value.ToString());
			}
		}

	}
}
