/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Destroy all trees in a %Radius unit circle around %Target")]
	public partial class DestroyTrees : TargetedAction
	{
		public DestroyTrees(KeyValue kv)
			: base(kv)
		{
		}
		public DestroyTrees(string className)
			: base(className)
		{
		}
		[Category("Misc")]
		[Description("float")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue Radius
		{
			get
			{
				KeyValue kv = GetSubkey("Radius");
				return (kv == null ? new NumberValue("Radius") : kv.GetNumberValue());
			}
			set
			{
				KeyValue kv = GetSubkey("Radius");
				if(kv == null)
				{
					kv = new KeyValue("Radius");
					KeyValue.AddChild(kv);
				}
				kv.Set(value);
			}
		}

	}
}
