/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("If the caster is alive, do %OnSuccess actions.  Else, do %OnFailure actions")]
	public partial class IsCasterAlive : BaseAction
	{
		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(typeof(ActionCollection), "Default")]
		public ActionCollection OnSuccess
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(typeof(ActionCollection), "Default")]
		public ActionCollection OnFailure
		{
			get;
			set;
		}

	}
}
