/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Knock back %Target units by %Distance units.  Throw them %Height units in the air for %Duration seconds.  Using fixed distance %IsFixedDistance")]
	public partial class Knockback : TargetedAction
	{
		[Category("Misc")]
		[Description("probably null")]
		[DefaultValue("")]
		public string Center
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("int")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue Distance
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("bool")]
		[DefaultValue(false)]
		public bool IsFixedDistance
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("int")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue Height
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("int")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue Duration
		{
			get;
			set;
		}

	}
}
