/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	public partial class LevelUpAbility : TargetedAction
	{
		[Category("Misc")]
		[Description("Name")]
		[DefaultValue("")]
		public string AbilityName
		{
			get;
			set;
		}

	}
}
