/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Move %Target to %MoveToTarget")]
	public partial class MoveUnit : TargetedAction
	{
		public MoveUnit(KeyValue kv)
			: base(kv)
		{
		}
		public MoveUnit(string className)
			: base(className)
		{
		}
		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(null)]
		public TargetKey MoveToTarget
		{
			get
			{
				return default(TargetKey);
			}
			set
			{
				KeyValue kv = GetSubkey("MoveToTarget");
				if(kv == null)
				{
					kv = new KeyValue("MoveToTarget");
					KeyValue.AddChild(kv);
				}
				kv.Set(value.ToString());
			}
		}

	}
}
