/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	public partial class RandomAction : TargetedAction
	{
		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(".5")]
		public string Chance
		{
			get;
			set;
		}

		public enum PseudoRandomEnum
		{
			DOTA_PSEUDO_RANDOM_BREWMASTER_CRIT,
			DOTA_PSEUDO_RANDOM_CHAOS_CRIT,
			DOTA_PSEUDO_RANDOM_FACELESS_BASH,
			DOTA_PSEUDO_RANDOM_ITEM_ABYSSAL,
			DOTA_PSEUDO_RANDOM_ITEM_BASHER,
			DOTA_PSEUDO_RANDOM_ITEM_BUTTERFLY,
			DOTA_PSEUDO_RANDOM_ITEM_GREATERCRIT,
			DOTA_PSEUDO_RANDOM_ITEM_HALBRED_MAIM,
			DOTA_PSEUDO_RANDOM_ITEM_LESSERCRIT,
			DOTA_PSEUDO_RANDOM_ITEM_MAELSTROM,
			DOTA_PSEUDO_RANDOM_ITEM_MJOLLNIR,
			DOTA_PSEUDO_RANDOM_ITEM_MJOLLNIR_STATIC,
			DOTA_PSEUDO_RANDOM_ITEM_MKB,
			DOTA_PSEUDO_RANDOM_ITEM_PMS,
			DOTA_PSEUDO_RANDOM_ITEM_SANGE_MAIM,
			DOTA_PSEUDO_RANDOM_ITEM_SANGEYASHA_MAIM,
			DOTA_PSEUDO_RANDOM_ITEM_STOUT,
			DOTA_PSEUDO_RANDOM_ITEM_VANGUARD,
			DOTA_PSEUDO_RANDOM_JUGG_CRIT,
			DOTA_PSEUDO_RANDOM_LYCAN_CRIT,
			DOTA_PSEUDO_RANDOM_PHANTOMASSASSIN_CRIT,
			DOTA_PSEUDO_RANDOM_SKELETONKING_CRIT,
			DOTA_PSEUDO_RANDOM_SLARDAR_BASH,
			DOTA_PSEUDO_RANDOM_SNIPER_HEADSHOT,
			DOTA_PSEUDO_RANDOM_TROLL_BASH,
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(PseudoRandomEnum.DOTA_PSEUDO_RANDOM_JUGG_CRIT)]
		public PseudoRandomEnum PseudoRandom
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(null)]
		public ActionCollection OnSuccess
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(null)]
		public ActionCollection OnFailure
		{
			get;
			set;
		}

	}
}
