/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Remove %AbilityName from %Target")]
	public partial class RemoveAbility : TargetedAction
	{
		public RemoveAbility(KeyValue kv)
			: base(kv)
		{
		}
		public RemoveAbility(string className)
			: base(className)
		{
		}
		[Category("Misc")]
		[Description("Name")]
		[DefaultValue("")]
		public string AbilityName
		{
			get
			{
				KeyValue kv = GetSubkey("AbilityName");
				return (kv == null ? "" : kv.GetString());
			}
			set
			{
				GetSubkey("AbilityName").Set(value.ToString());
			}
		}

	}
}
