/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Replace %Target with %UnitName")]
	public partial class ReplaceUnit : TargetedAction
	{
		[Category("Misc")]
		[Description("Unit Name")]
		[DefaultValue("")]
		public string UnitName
		{
			get;
			set;
		}

	}
}
