/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Replace %Target with %UnitName")]
	public partial class ReplaceUnit : TargetedAction
	{
		public ReplaceUnit(KeyValue kv)
			: base(kv)
		{
		}
		public ReplaceUnit(string className)
			: base(className)
		{
		}
		[Category("Misc")]
		[Description("Unit Name")]
		[DefaultValue("")]
		public string UnitName
		{
			get
			{
				KeyValue kv = GetSubkey("UnitName");
				return (kv == null ? "" : kv.GetString());
			}
			set
			{
				KeyValue kv = GetSubkey("UnitName");
				if(kv == null)
				{
					kv = new KeyValue("UnitName");
					KeyValue.AddChild(kv);
				}
				kv.Set(value);
			}
		}

	}
}
