/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Respawn %Target hero")]
	public partial class RespawnHero : TargetedAction
	{
		public RespawnHero(KeyValue kv)
			: base(kv)
		{
		}
		public RespawnHero(string className)
			: base(className)
		{
		}
	}
}
