/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Run Lua function %Function defined in %ScriptFile")]
	public partial class RunScript : BaseAction
	{
		public RunScript(KeyValue kv)
			: base(kv)
		{
		}
		public RunScript(string className)
			: base(className)
		{
		}
		[Category("Misc")]
		[Description("filename")]
		[DefaultValue("")]
		public string ScriptFile
		{
			get
			{
				KeyValue kv = GetSubkey("ScriptFile");
				return (kv == null ? "" : kv.GetString());
			}
			set
			{
				GetSubkey("ScriptFile").Set(value.ToString());
			}
		}

		[Category("Misc")]
		[Description("filename")]
		[DefaultValue("")]
		public string Function
		{
			get
			{
				KeyValue kv = GetSubkey("Function");
				return (kv == null ? "" : kv.GetString());
			}
			set
			{
				GetSubkey("Function").Set(value.ToString());
			}
		}

	}
}
