/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Spawn %UnitCount %UnitName around %Target with a radius of %Radius units for %Duration seconds.  After spawn, execute %OnSpawn actions")]
	public partial class SpawnUnit : TargetedAction
	{
		public SpawnUnit(KeyValue kv)
			: base(kv)
		{
		}
		public SpawnUnit(string className)
			: base(className)
		{
		}
		[Category("Misc")]
		[Description("Name")]
		[DefaultValue("")]
		public string UnitName
		{
			get
			{
				KeyValue kv = GetSubkey("UnitName");
				return (kv == null ? "" : kv.GetString());
			}
			set
			{
				GetSubkey("UnitName").Set(value.ToString());
			}
		}

		[Category("Misc")]
		[Description("int")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue UnitCount
		{
			get
			{
				return default(NumberValue);
			}
			set
			{
				GetSubkey("UnitCount").Set(value.ToString());
			}
		}

		[Category("Misc")]
		[Description("int")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue SpawnRadius
		{
			get
			{
				return default(NumberValue);
			}
			set
			{
				GetSubkey("SpawnRadius").Set(value.ToString());
			}
		}

		[Category("Misc")]
		[Description("int")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue Duration
		{
			get
			{
				return default(NumberValue);
			}
			set
			{
				GetSubkey("Duration").Set(value.ToString());
			}
		}

		[Category("Misc")]
		[Description("Name")]
		[DefaultValue(typeof(ActionCollection), "OnSpawn")]
		public ActionCollection OnSpawn
		{
			get
			{
				return default(ActionCollection);
			}
			set
			{
				GetSubkey("OnSpawn").Set(value.ToString());
			}
		}

	}
}
