/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Spend 1 charge when this item is used")]
	public partial class SpendCharge : BaseAction
	{
		public SpendCharge(KeyValue kv)
			: base(kv)
		{
		}
		public SpendCharge(string className)
			: base(className)
		{
		}
	}
}
