/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Stun %Target for %Duration seconds")]
	public partial class Stun : TargetedAction
	{
		public Stun(KeyValue kv)
			: base(kv)
		{
		}
		public Stun(string className)
			: base(className)
		{
		}
		[Category("Misc")]
		[Description("float")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue Duration
		{
			get
			{
				return default(NumberValue);
			}
			set
			{
				GetSubkey("Duration").Set(value.ToString());
			}
		}

	}
}
