/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Stun %Target for %Duration seconds")]
	public partial class Stun : TargetedAction
	{
		[Category("Misc")]
		[Description("float")]
		[DefaultValue("")]
		public string Duration
		{
			get;
			set;
		}

	}
}
