/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;
using KVLib;

namespace WorldSmith.DataClasses
{
	public partial class TargetedAction : BaseAction
	{
		public TargetedAction(KeyValue kv)
			: base(kv)
		{
		}
		public TargetedAction(string className)
			: base(className)
		{
		}
		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(null)]
		public TargetKey Target
		{
			get
			{
				KeyValue kv = GetSubkey("Target");
				return (kv == null ? new TargetKey() : kv.GetTargetKey());
			}
			set
			{
				KeyValue kv = GetSubkey("Target");
				if(kv == null)
				{
					kv = new KeyValue("Target");
					KeyValue.AddChild(kv);
				}
				kv.Set(value);
			}
		}

	}
}
