/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;
using WorldSmith.Panels;
using WorldSmith.Dialogs;

namespace WorldSmith.DataClasses
{
	[DotaAction]
	[EditorGrammar("Fire a Tracking projectile at the target that is dodgable %Dodgeable with the effect %EffectName and moves at %MoveSpeed units per second.  It provides vision %ProvidesVision of %VisionRadius units")]
	public partial class TrackingProjectile : BaseAction
	{
		[Category("Misc")]
		[Description("bool")]
		[DefaultValue(false)]
		public bool Dodgeable
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("bool")]
		[DefaultValue(false)]
		public bool ProvidesVision
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("int")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue VisionRadius
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("Effect Name")]
		[DefaultValue("")]
		public string EffectName
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("int")]
		[DefaultValue(typeof(NumberValue), "")]
		public NumberValue MoveSpeed
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("?")]
		[DefaultValue("")]
		public string SourceAttachment
		{
			get;
			set;
		}

	}
}
