//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldSmith.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorldSmith.Resources.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ability Editor.
        /// </summary>
        public static string abilityTabTitle {
            get {
                return ResourceManager.GetString("abilityTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addon Config.
        /// </summary>
        public static string addonConfigTitle {
            get {
                return ResourceManager.GetString("addonConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addon.
        /// </summary>
        public static string addonToolStripMenuItem1 {
            get {
                return ResourceManager.GetString("addonToolStripMenuItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addon.
        /// </summary>
        public static string addontToolStripMenuItem {
            get {
                return ResourceManager.GetString("addontToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string englishToolStripMenuItem {
            get {
                return ResourceManager.GetString("englishToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string fileMenuExit {
            get {
                return ResourceManager.GetString("fileMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string fileMenuNew {
            get {
                return ResourceManager.GetString("fileMenuNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string fileMenuOpen {
            get {
                return ResourceManager.GetString("fileMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string fileMenuSave {
            get {
                return ResourceManager.GetString("fileMenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string fileMenuTitle {
            get {
                return ResourceManager.GetString("fileMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Editor.
        /// </summary>
        public static string itemTabTible {
            get {
                return ResourceManager.GetString("itemTabTible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string optionsMenuLanguage {
            get {
                return ResourceManager.GetString("optionsMenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string optionsMenuTitle {
            get {
                return ResourceManager.GetString("optionsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Dota Directory.
        /// </summary>
        public static string optionsSetDotaFolder {
            get {
                return ResourceManager.GetString("optionsSetDotaFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish (Svenska).
        /// </summary>
        public static string swedishToolStripMenuItem {
            get {
                return ResourceManager.GetString("swedishToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wibble Editor.
        /// </summary>
        public static string unitTabTitle {
            get {
                return ResourceManager.GetString("unitTabTitle", resourceCulture);
            }
        }
    }
}
