/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;

namespace WorldSmith.DataClasses
{
    class DotaUnit : DotaBaseUnit
    {
        [Category("Misc")]
        [Description("No Description Set")]
        [DefaultValue(false)]
        public bool IsAncient
        {
            get;
            set;
        }

        [Category("Misc")]
        [Description("No Description Set")]
        [DefaultValue(false)]
        public bool IsNeutralUnitType
        {
            get;
            set;
        }

        [Category("Misc")]
        [Description("No Description Set")]
        [DefaultValue("")]
        public string SelectionGroup
        {
            get;
            set;
        }

        [Category("Misc")]
        [Description("No Description Set")]
        [DefaultValue(false)]
        public bool SelectOnSpawn
        {
            get;
            set;
        }

        [Category("Misc")]
        [Description("No Description Set")]
        [DefaultValue(true)]
        public bool CanBeDominated
        {
            get;
            set;
        }

        [Category("Misc")]
        [Description("No Description Set")]
        [DefaultValue(false)]
        public bool IgnoreAddSummonedToSelection
        {
            get;
            set;
        }

        [Category("Misc")]
        [Description("No Description Set")]
        [DefaultValue(true)]
        public bool AutoAttacksByDefault
        {
            get;
            set;
        }

        [Category("Misc")]
        [Description("No Description Set")]
        [DefaultValue(250)]
        public int AttackRangeBuffer
        {
            get;
            set;
        }

        [Category("Misc")]
        [Description("No Description Set")]
        [DefaultValue(100)]
        public int FollowRange
        {
            get;
            set;
        }

        [Category("Misc")]
        [Description("No Description Set")]
        [DefaultValue(1.0)]
        public float AttackDesire
        {
            get;
            set;
        }

        [Category("Misc")]
        [Description("No Description Set")]
        [DefaultValue(true)]
        public bool WakesNeutrals
        {
            get;
            set;
        }

    }
}
