/*****************************  NOTICE  ********************************************
* This file was autogenerated.  Do not edit.                                       *
* Instead, modify the schema in DataSchema related to this class and regenerate it *
***********************************************************************************/
using System;
using System.ComponentModel;

namespace WorldSmith.DataClasses
{
	class DotaItem : DotaAbility
	{
		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(0)]
		public int ItemCost
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(0)]
		public int ItemInitialCharges
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(true)]
		public bool ItemCombinable
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(true)]
		public bool ItemPermanent
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(false)]
		public bool ItemStackable
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(false)]
		public bool ItemRecipe
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(true)]
		public bool ItemDroppable
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(true)]
		public bool ItemPurchasable
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(true)]
		public bool ItemSellable
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(false)]
		public bool ItemRequiresCharges
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(true)]
		public bool ItemKillable
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(false)]
		public bool ItemDisassemblable
		{
			get;
			set;
		}

		public enum ItemShareabilityEnum
		{
			ITEM_PARTIALLY_SHAREABLE,
			ITEM_FULLY_SHAREABLE,
			ITEM_FULLY_SHAREABLE_STACKING,
			ITEM_NOT_SHAREABLE,
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(ItemShareabilityEnum.ITEM_NOT_SHAREABLE)]
		public ItemShareabilityEnum ItemShareability
		{
			get;
			set;
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(false)]
		public bool ItemDeclaresPurchase
		{
			get;
			set;
		}

		[Flags]
		public enum ItemDeclarationsFlags
		{
			DECLARE_PURCHASES_NONE = 0,
			DECLARE_PURCHASES_IN_SPEECH = 1,
			DECLARE_PURCHASES_TO_SPECTATORS = 2,
			DECLARE_PURCHASES_TO_TEAMMATES = 4,
		}

		[Category("Misc")]
		[Description("No Description Set")]
		[DefaultValue(ItemDeclarationsFlags.DECLARE_PURCHASES_NONE)]
		public ItemDeclarationsFlags ItemDeclarations
		{
			get;
			set;
		}

	}
}
